name: Build Debian package

on:
  push:
    branches:
      - branchAutoPackage
  pull_request:
    branches:
      - branchAutoPackage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y dpkg-dev

    - name: Build Debian package
      run: |
        dpkg-buildpackage -us -uc

