name: CI for C++ project

on:
  push:
    branches:
      - main
      - branchAutoTest  # Якщо в тебе є інша гілка для тестів
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up C++ build environment
        run: sudo apt-get update && sudo apt-get install -y g++ cmake libgtest-dev

      - name: Build the project
        run: |
          make clean
          make

      - name: Run tests
        run: make check
